#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QLKHO.Android.Resource", IsApplication=true)]

namespace QLKHO.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Business.Resource.String.ApplicationName = global::QLKHO.Android.Resource.String.ApplicationName;
			global::Business.Resource.String.Hello = global::QLKHO.Android.Resource.String.Hello;
			global::DataTransferObject.Resource.String.ApplicationName = global::QLKHO.Android.Resource.String.ApplicationName;
			global::DataTransferObject.Resource.String.Hello = global::QLKHO.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bikini = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int HangHoa = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Home = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Search = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ThongKe = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int btnDangNhap = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int btnImgExpander = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int edtPassWord = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int edtUserName = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int ivMenuImg = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int menuIconImgView = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int menuListView = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int titleBarLinearLayout = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int txt1 = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int txtActionBarText = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int txtDescription = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int txtMnuText = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int txtPage = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DangNhap = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuCustomLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int HangHoa = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ThongKe = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int TimKiem = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
