#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QLKHO.Android.Resource", IsApplication=true)]

namespace QLKHO.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Business.Resource.String.ApplicationName = global::QLKHO.Android.Resource.String.ApplicationName;
			global::Business.Resource.String.Hello = global::QLKHO.Android.Resource.String.Hello;
			global::DataTransferObject.Resource.String.ApplicationName = global::QLKHO.Android.Resource.String.ApplicationName;
			global::DataTransferObject.Resource.String.Hello = global::QLKHO.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int list = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bikini = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DangKy = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int HangHoa = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Kho = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ThongKe = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int DiaChiKho = 2131099659;
			
			// aapt resource value: 0x7f06002d
			public const int MaHH = 2131099693;
			
			// aapt resource value: 0x7f060030
			public const int MaKho = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int MaNV = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int MoTa = 2131099695;
			
			// aapt resource value: 0x7f06000c
			public const int NhanVien = 2131099660;
			
			// aapt resource value: 0x7f06002e
			public const int TenHH = 2131099694;
			
			// aapt resource value: 0x7f06000a
			public const int TenKho = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int addr = 2131099650;
			
			// aapt resource value: 0x7f060019
			public const int btnDangKy = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public const int btnDangNhap = 2131099676;
			
			// aapt resource value: 0x7f060027
			public const int btnImgExpander = 2131099687;
			
			// aapt resource value: 0x7f060009
			public const int del = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int delivery = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int details = 2131099648;
			
			// aapt resource value: 0x7f06001b
			public const int edtPassWord = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int edtUserName = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int edtsearch = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int fragmentContainer = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int fragmentContainerKho = 2131099681;
			
			// aapt resource value: 0x7f06002c
			public const int icon = 2131099692;
			
			// aapt resource value: 0x7f06002a
			public const int ivMenuImg = 2131099690;
			
			// aapt resource value: 0x7f06001f
			public const int lvKho = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int lvhanghoa = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int menuIconImgView = 2131099683;
			
			// aapt resource value: 0x7f060028
			public const int menuListView = 2131099688;
			
			// aapt resource value: 0x7f060001
			public const int name = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int rdNam = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int rdNu = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int save = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int scrollView1 = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int sit_down = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int spiner1 = 2131099670;
			
			// aapt resource value: 0x7f060004
			public const int take_out = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int textView6 = 2131099667;
			
			// aapt resource value: 0x7f060022
			public const int titleBarLinearLayout = 2131099682;
			
			// aapt resource value: 0x7f060029
			public const int txt1 = 2131099689;
			
			// aapt resource value: 0x7f060024
			public const int txtActionBarText = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int txtDescription = 2131099686;
			
			// aapt resource value: 0x7f060010
			public const int txtDiaChi = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int txtEmail = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int txtMatKhau = 2131099672;
			
			// aapt resource value: 0x7f06002b
			public const int txtMnuText = 2131099691;
			
			// aapt resource value: 0x7f060012
			public const int txtNgaySinh = 2131099666;
			
			// aapt resource value: 0x7f060025
			public const int txtPage = 2131099685;
			
			// aapt resource value: 0x7f06000f
			public const int txtSDT = 2131099663;
			
			// aapt resource value: 0x7f060017
			public const int txtTaiKhoan = 2131099671;
			
			// aapt resource value: 0x7f06000e
			public const int txtTen = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int types = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int update = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChiTietHH = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CT_Kho = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DangKy = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DangNhap = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DSHangHoa = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DSKho = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HangHoa = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Kho = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MenuCustomLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Row = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Row_Kho = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int DangKy = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int HangHoa = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int Kho = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int ThongKe = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int TimKiem = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
